package org.chipay.cat;

import org.springframework.stereotype.Component;

/**
 * TODO: implement me
 */
@Component
public class RestApiCatService implements CatService {

    @Override
    public String getFact() {
        return null; // TODO: autogenerated
    }
}
